[prompt1]
input_prompt = """
Analyse les textes extraits de deux images de chèque : recto et verso. Ton objectif est de généraliser l'extraction pour tout type de chèque, en tenant compte des variations de disposition, des formats et des erreurs courantes des OCR. Compare les résultats de deux OCR (TrOCR et Qari-OCR) et sélectionne la meilleure valeur pour chaque champ en fonction du contexte. Si un champ est incertain ou non détecté, marque-le comme "Non détecté".

Champs à extraire :
- Rib1 : un numéro de 20 chiffres généralement au recto du chèque, associé au propriétaire du chèque.
- Rib2 : un numéro de 20 chiffres généralement au verso du chèque, associé au receveur (non présent au recto).
- nom : nom du propriétaire du chèque (personne ou société), imprimé, pas manuscrit.
- nomreciver : nom du receveur, manuscrit sur le chèque.
- plafond : montant en chiffres, imprimé sur le chèque.
- num_cheque : numéro du chèque, imprimé.
- montant : montant manuscrit en texte et chiffres, généralement en haut à droite du chèque.
- date : date manuscrite, généralement en bas à droite du chèque.

Retourne les résultats sous forme de JSON avec chaque champ et sa valeur.
"""

[google]
api_key = "AIzaSyC9dl-4OKZbDXImTATzINmI8Azx9cY8EjA"